"""Security core: password hashing, password policy, and JWT utilities.

Phase 5G. This is shared SuperTeacher infrastructure (Step 41) — the auth
service, the identity dependencies and future modules (teacher/parent/admin
account flows, password change) all consume it. Token construction lives
*only* here: no API route or service builds or decodes a JWT directly.

Password hashing uses **Argon2id** via ``argon2-cffi`` (a modern, maintained
library; deliberately not the desktop application's SHA-256 scheme). Hashes
are stored as PHC strings in ``users.password_hash``; plaintext never
persists, is never logged, and never appears in a schema.

JWTs are compact HS256 tokens signed with the environment-provided
``SECRET_KEY`` (validated by ``Settings.jwt_secret``). Claims are limited to
identity/authorization facts (sub, role, token type, iat, exp) — never a
password or profile/catalog payload (Step 6).
"""
from __future__ import annotations

import uuid
from datetime import datetime, timedelta, timezone
from typing import Any, Literal

import jwt
from argon2 import PasswordHasher
from argon2.exceptions import InvalidHashError, VerificationError, VerifyMismatchError

from app.core.config import get_settings

# --- password hashing (Argon2id) -------------------------------------------------

# argon2-cffi defaults are already OWASP-aligned Argon2id parameters; the
# hasher is module-level because construction is not free and the object is
# stateless/thread-safe for hashing and verification.
_password_hasher = PasswordHasher()

TokenType = Literal["access", "refresh", "reset", "invite"]


def hash_password(password: str) -> str:
    """Hash a plaintext password into a PHC-format Argon2id string.

    The salt is generated by the library; the result embeds algorithm and
    cost parameters, so future rehashing/parameter upgrades need no schema
    change. Empty strings are rejected here as a last line of defense (the
    schema-level policy already refuses them).
    """
    if not password:
        raise ValueError("password must not be empty")
    return _password_hasher.hash(password)


def verify_password(password: str, password_hash: str) -> bool:
    """Check a plaintext password against a stored Argon2id hash.

    Never raises for bad credentials: an invalid or corrupted stored hash
    simply fails verification (returning False), so a malformed row can
    never crash a login request.
    """
    if not password or not password_hash:
        return False
    try:
        return _password_hasher.verify(password_hash, password)
    except (VerifyMismatchError, VerificationError, InvalidHashError):
        return False


# --- password policy (Step 3) ------------------------------------------------------

class PasswordPolicyError(ValueError):
    """The supplied password violates the server-side password policy."""


def validate_password_policy(password: str) -> str:
    """Validate (and return) a candidate password, or raise PasswordPolicyError.

    The policy is deliberately minimal and usable:

    - required, non-empty after stripping;
    - at least ``Settings.PASSWORD_MIN_LENGTH`` characters (8 by default).

    No composition rules (digits/symbols): length is the dominant factor for
    entropy and composition rules demonstrably harm usability. Callers must
    never log the password or include it in an error message.
    """
    if password is None:
        raise PasswordPolicyError("password is required")
    candidate = password.strip()
    if not candidate:
        raise PasswordPolicyError("password must not be empty")
    minimum = get_settings().PASSWORD_MIN_LENGTH
    if len(candidate) < minimum:
        raise PasswordPolicyError(
            f"password must be at least {minimum} characters long"
        )
    return candidate


# --- JWT utilities (Steps 6, 10) ------------------------------------------------------

def create_access_token(
    user_id: uuid.UUID,
    role: str,
    expires_minutes: int | None = None,
) -> str:
    """Issue a short-lived access token for one user.

    Claims (deliberately minimal — identity/authorization only):

    - ``sub``: the user's UUID (string form);
    - ``role``: the user's role at issue time;
    - ``typ``: ``"access"`` (other token types are rejected on decode);
    - ``jti``: unique token identifier (UUID) for audit trail and future
      revocation support;
    - ``iat`` / ``exp``: issued-at and expiry, timezone-aware epoch seconds.
    """
    settings = get_settings()
    now = datetime.now(timezone.utc)
    lifetime = expires_minutes if expires_minutes is not None else settings.ACCESS_TOKEN_EXPIRE_MINUTES
    claims: dict[str, Any] = {
        "sub": str(user_id),
        "role": role,
        "typ": "access",
        "jti": str(uuid.uuid4()),
        "iat": now,
        "exp": now + timedelta(minutes=lifetime),
    }
    return jwt.encode(claims, settings.jwt_secret, algorithm="HS256")


def create_refresh_token(
    user_id: uuid.UUID,
    session_id: uuid.UUID,
    expires_days: int | None = None,
) -> str:
    """Issue a refresh token bound to a revocable ``auth_sessions`` row.

    The JWT itself carries ``typ=refresh`` plus the session id (``sid``) so
    the auth service can locate and enforce the server-side session state
    (expiry, revocation) — the signed token alone never grants access.
    """
    settings = get_settings()
    now = datetime.now(timezone.utc)
    lifetime = expires_days if expires_days is not None else settings.REFRESH_TOKEN_EXPIRE_DAYS
    claims: dict[str, Any] = {
        "sub": str(user_id),
        "sid": str(session_id),
        "typ": "refresh",
        "jti": str(uuid.uuid4()),
        "iat": now,
        "exp": now + timedelta(days=lifetime),
    }
    return jwt.encode(claims, settings.jwt_secret, algorithm="HS256")


def decode_token(token: str, expected_type: TokenType) -> dict[str, Any]:
    """Decode and validate a JWT, returning its claims.

    Enforces signature, expiry, algorithm and the expected ``typ`` claim.
    Raises :class:`InvalidTokenError` (a ValueError) on any failure —
    callers translate that into the generic 401 contract; the raw decoding
    internals never reach a client.
    """
    settings = get_settings()
    try:
        claims: dict[str, Any] = jwt.decode(
            token,
            settings.jwt_secret,
            algorithms=["HS256"],  # pin the algorithm — never trust token headers
        )
    except jwt.ExpiredSignatureError as exc:
        raise jwt.InvalidTokenError("token has expired") from exc
    except jwt.MissingRequiredClaimError as exc:
        raise jwt.InvalidTokenError("token is missing required claims") from exc

    if claims.get("typ") != expected_type:
        raise jwt.InvalidTokenError("unexpected token type")
    if not claims.get("sub"):
        raise jwt.InvalidTokenError("token has no subject")
    return claims


# Re-export PyJWT's InvalidTokenError so callers can catch it cleanly.
InvalidTokenError = jwt.InvalidTokenError


def create_reset_token(user_id: uuid.UUID, expires_minutes: int = 60) -> str:
    """Issue a short-lived password-reset token for one user.

    Claims: sub (user UUID), typ="reset", jti, iat, exp (1 hour default).
    The raw token is returned to the caller (to embed in a URL or send via
    email); the server tracks it via a ``password_reset_tokens`` row
    (SHA-256 digest) for revocation and single-use enforcement.
    """
    settings = get_settings()
    now = datetime.now(timezone.utc)
    claims: dict[str, Any] = {
        "sub": str(user_id),
        "typ": "reset",
        "jti": str(uuid.uuid4()),
        "iat": now,
        "exp": now + timedelta(minutes=expires_minutes),
    }
    return jwt.encode(claims, settings.jwt_secret, algorithm="HS256")


def create_invite_token(user_id: uuid.UUID, expires_minutes: int = 72 * 60) -> str:
    """Issue a teacher-invitation token for one pending account.

    Claims: sub (user UUID), typ="invite", jti, iat, exp (72 hours default).
    The raw token goes to the invitation email only; the server keeps its
    SHA-256 digest in ``invite_tokens`` for single-use enforcement — the
    raw value is never logged, stored or returned by any API response.
    """
    settings = get_settings()
    now = datetime.now(timezone.utc)
    claims: dict[str, Any] = {
        "sub": str(user_id),
        "typ": "invite",
        "jti": str(uuid.uuid4()),
        "iat": now,
        "exp": now + timedelta(minutes=expires_minutes),
    }
    return jwt.encode(claims, settings.jwt_secret, algorithm="HS256")


__all__ = [
    "PasswordPolicyError",
    "TokenType",
    "hash_password",
    "verify_password",
    "validate_password_policy",
    "create_access_token",
    "create_refresh_token",
    "decode_token",
    "create_reset_token",
    "create_invite_token",
    "InvalidTokenError",
]
